---
title: "BIOL 452 Appendix"
author: "Kat Chhen"
output: html_document
date: "2023-04-17"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r message = FALSE}
#load packages
#data, visualization
library(readr)
library(ggplot2)
library(khroma)          #colour blind friendly colour palette
library(dplyr)           #data wrangling
library(tidyr)           #data wrangling
library(lubridate)       #round_date() for corrMove
#analysis
library(ctmm)            #continuous-time movement models
library(lme4)            #pairwise sex test to see if differences are significant using glmer()
devtools::install_github("jmcalabrese/corrMove", force = TRUE)
library(corrMove)
```

#Load RDS files

```{r}
# Set working directory
setwd("C:/Users/achhen/OneDrive - UBC/Github/giant-anteater")

#movement models
FIT_1 <- readRDS("RDS/movement model/FIT_1.RDS")
FIT_1_male <- readRDS("RDS/movement model/FIT_1_male.RDS")
FIT_1_male_adult <- readRDS("RDS/movement model/FIT_1_male_adult.RDS")
FIT_1_female <- readRDS("RDS/movement model/FIT_1_female.RDS")
FIT_2 <- readRDS("RDS/movement model/FIT_2.RDS")
FIT_2_male <- readRDS("RDS/movement model/FIT_2_male.RDS")
FIT_2_male_adult <- readRDS("RDS/movement model/FIT_2_male_adult.RDS")
FIT_2_female <- readRDS("RDS/movement model/FIT_2_female.RDS")
#AKDE overlap
AKDE_1 <- readRDS("RDS/movement model/AKDE_1.RDS")
AKDE_1_male <- readRDS("RDS/movement model/AKDE_1_male.RDS")
AKDE_1_male_adult <- readRDS("RDS/movement model/AKDE_1_male_adult.RDS")
AKDE_1_female <- readRDS("RDS/movement model/AKDE_1_female.RDS")
AKDE_2 <- readRDS("RDS/movement model/AKDE_2.RDS")
AKDE_2_male <- readRDS("RDS/movement model/AKDE_2_male.RDS")
AKDE_2_male_adult <- readRDS("RDS/movement model/AKDE_2_male_adult.RDS")
AKDE_2_female <- readRDS("RDS/movement model/AKDE_2_female.RDS")

#pairwise dataframe
DATA_pairwise_1 <- readRDS("RDS/pairwise/DATA_pairwise_1.RDS")
DATA_pairwise_1_adult <- readRDS("RDS/pairwise/DATA_pairwise_1_adult.RDS")
DATA_pairwise_2 <- readRDS("RDS/pairwise/DATA_pairwise_2.RDS")
DATA_pairwise_2_adult <- readRDS("RDS/pairwise/DATA_pairwise_2_adult.RDS")
DATA_pairwise <- readRDS("RDS/pairwise/DATA_pairwise.RDS")

#proximity analysis
DATA_proximity_1 <- readRDS("RDS/proximity/DATA_proximity_1.RDS")
DATA_proximity_2 <- readRDS("RDS/proximity/DATA_proximity_2.RDS")
DATA_proximity <- readRDS("RDS/proximity/DATA_proximity.RDS")

#distance
distance1 <- readRDS("RDS/distance/distance_pair1.RDS")
distance2 <- readRDS("RDS/distance/distance_pair2.RDS")
distance3 <- readRDS("RDS/distance/distance_pair3.RDS")
distance4 <- readRDS("RDS/distance/distance_pair4.RDS")
distance5 <- readRDS("RDS/distance/distance_pair5.RDS")
distance6 <- readRDS("RDS/distance/distance_pair6.RDS")
distance7 <- readRDS("RDS/distance/distance_pair7.RDS")
distance8 <- readRDS("RDS/distance/distance_pair8.RDS")
distance9 <- readRDS("RDS/distance/distance_pair9.RDS")
distance10 <- readRDS("RDS/distance/distance_pair10.RDS")
distance11 <- readRDS("RDS/distance/distance_pair11.RDS")
distance12 <- readRDS("RDS/distance/distance_pair12.RDS")

#correlative movement
cmAnteater_pair3 <- readRDS("RDS/correlative movement/cmAnteater_pair3.RDS")
cmAnteater_pair2 <- readRDS("RDS/correlative movement/cmAnteater_pair2.RDS")
cmAnteater_pair1 <- readRDS("RDS/correlative movement/cmAnteater_pair1.RDS")
cmAnteater_pair4 <- readRDS("RDS/correlative movement/cmAnteater_pair4.RDS")
cmAnteater_pair5 <- readRDS("RDS/correlative movement/cmAnteater_pair5.RDS")
cmAnteater_pair6 <- readRDS("RDS/correlative movement/cmAnteater_pair6.RDS")
cmAnteater_pair7 <- readRDS("RDS/correlative movement/cmAnteater_pair7.RDS")
cmAnteater_pair8 <- readRDS("RDS/correlative movement/cmAnteater_pair8.RDS")
cmAnteater_pair9 <- readRDS("RDS/correlative movement/cmAnteater_pair9.RDS")
cmAnteater_pair10 <- readRDS("RDS/correlative movement/cmAnteater_pair10.RDS")
cmAnteater_pair11 <- readRDS("RDS/correlative movement/cmAnteater_pair11.RDS")
cmAnteater_pair12 <- readRDS("RDS/correlative movement/cmAnteater_pair12.RDS")
```



# Methods



## Data Preparation

```{r}
# Import dataset
anteater_DATA <- read_csv("data/Anteaters_NoOutliers (original data).csv", col_types = cols(timestamp = "c", class = "c", identity = "c", id = "c", .default = "d"))

# Convert dataset to a telemetry object
DATA <- as.telemetry("data/Anteaters_NoOutliers (original data).csv")

# Import biological dataset (supplementry data)
METADATA <- read_csv("data/Anteater_Results_Final.csv")
#correct a mismatch entry for 'Larry 267' and 'Larry'
METADATA <- mutate(select(METADATA, 1:3), ID = if_else(condition = ID == 'Larry',
                                                       true = 'Larry 267',
                                                       false = ID))

## TEMPERATURE DATA
TEMPDATA <- read_csv("data/anteater_annotated.csv")
names(TEMPDATA)[19] <- "temperature"

#data subsetting and carpentry
site_1 <- DATA[c(1,3,9,10,12,15,21,24,27,29,36,38)] # male and female (n=12)
site_1_adult <- DATA[c(1,9,10,12,15,21,29,36,38)] # adult (n=9)
site_1_male <- DATA[c(1,3,12,21,24,27,38)] # male (n=7)
site_1_male_adult <- DATA[c(1,12,21,38)] # male adult (n=4)
site_1_female <- DATA[c(9,10,15,29,36)] # female adult (n=5)
site_2 <- DATA[c(2,8,19,22,25,28,30,31,37,41,42)]
site_2_adult <- DATA[c(2,8,19,22,25,28,30,31,41,42)] 
site_2_male <- DATA[c(8,25,37,42,28)]
site_2_male_adult <- DATA[c(8,25,42,28)]
site_2_female <- DATA[c(2,22,30,19,31,41)]
```


## Data Analysis

### Home Range Overlap

#### Movement Models
##### Site 1

```{r}
#fit movement models
# SITE 1 - MALE AND FEMALE (n=12)
GUESS_1 <- lapply(site_1[1:12], function(b) ctmm.guess(b,interactive=FALSE) )
FIT_1 <- lapply(1:12, function(i) ctmm.select(site_1[[i]],GUESS_1[[i]]) )
names(FIT_1) <- names(site_1[1:12])
overlap(FIT_1)
#calculate AKDE overlap
AKDE_1 <- akde(site_1[1:12],FIT_1)
overlap(AKDE_1)

# SITE 1 - MALE (n=7)
GUESS_1_male <- lapply(site_1_male[1:7], function(b) ctmm.guess(b,interactive=FALSE) )
FIT_1_male <- lapply(1:7, function(i) ctmm.select(site_1_male[[i]],GUESS_1_male[[i]]) )
names(FIT_1_male) <- names(site_1_male[1:7])
overlap(FIT_1_male)
#calculate AKDE overlap
AKDE_1_male <- akde(site_1[1:7],FIT_1_male)
overlap(AKDE_1_male)

# SITE 1 - MALE ADULT (n=4)
GUESS_1_male_adult <- lapply(site_1[1:4], function(b) ctmm.guess(b,interactive=FALSE) )
FIT_1_male_adult <- lapply(1:4, function(i) ctmm.select(site_1_male_adult[[i]],GUESS_1_male_adult[[i]]) )
names(FIT_1_male_adult) <- names(site_1_male_adult[1:4])
overlap(FIT_1_male_adult)
#calculate AKDE overlap
AKDE_1_male_adult <- akde(site_1_male_adult[1:4],FIT_1_male_adult)
overlap(AKDE_1_male_adult)

# SITE 1 - FEMALE (n=5)
GUESS_1_female <- lapply(site_1_female[1:5], function(b) ctmm.guess(b,interactive=FALSE) )
FIT_1_female <- lapply(1:5, function(i) ctmm.select(site_1_female[[i]],GUESS_1_female[[i]]) )
names(FIT_1_female) <- names(site_1_female[1:5])
overlap(FIT_1_female)
#calculate AKDE overlap
AKDE_1_female <- akde(site_1_female[1:5],FIT_1_female)
overlap(AKDE_1_female)

#RDS of site 1 movement model and AKDE overlap have been saved to "RDS/movement model" folder
```

##### Site 2

```{r}
# SITE 2 - MALE AND FEMALE (n=11)
GUESS_2 <- lapply(site_2[1:11], function(b) ctmm.guess(b,interactive=FALSE) )
FIT_2 <- lapply(1:11, function(i) ctmm.select(site_2[[i]],GUESS_2[[i]]) )
names(FIT_2) <- names(site_2[1:11])
overlap(FIT_2)
#calculate AKDE overlap
AKDE_2 <- akde(site_2[1:11],FIT_2)
overlap(AKDE_2)

# SITE 2 - MALE (n=5)
GUESS_2_male <- lapply(site_2_male[1:5], function(b) ctmm.guess(b,interactive=FALSE) )
FIT_2_male <- lapply(1:5, function(i) ctmm.select(site_2_male[[i]],GUESS_2_male[[i]]) )
names(FIT_2_male) <- names(site_2_male[1:5])
overlap(FIT_2_male)
#calculate AKDE overlap
AKDE_2_male <- akde(site_2[1:5],FIT_2_male)
overlap(AKDE_2_male)

# SITE 2 - MALE ADULT (n=4)
GUESS_2_male_adult <- lapply(site_2_male_adult[1:4], function(b) ctmm.guess(b,interactive=FALSE) )
FIT_2_male_adult <- lapply(1:4, function(i) ctmm.select(site_2_male_adult[[i]],GUESS_2_male_adult[[i]]) )
names(FIT_2_male_adult) <- names(site_2_male_adult[1:4])
overlap(FIT_2_male_adult)
#calculate AKDE overlap
AKDE_2_male_adult <- akde(site_2_male_adult[1:4],FIT_2_male_adult)
overlap(AKDE_2_male_adult)

# SITE 2 - FEMALE (n=6)
GUESS_2_female <- lapply(site_2_female[1:6], function(b) ctmm.guess(b,interactive=FALSE) )
FIT_2_female <- lapply(1:6, function(i) ctmm.select(site_2_female[[i]],GUESS_2_female[[i]]) )
names(FIT_2_female) <- names(site_2_female[1:6])
overlap(FIT_2_female)
#calculate AKDE overlap
AKDE_2_female <- akde(site_2_female[1:6],FIT_2_female)
overlap(AKDE_2_female)

#RDS of site 2 movement model and AKDE overlap have been saved to "RDS/movement model" folder
```

#### Pairwise Sex Comparison of Home Range Overlaps

##### Pairwise data frame (Data wrangling)

```{r}
#Create pairwise data frame

#Site 1
# Create a data frame from the overlap values
#calculate 95% overlap
overlap_1 <- overlap(object = AKDE_1, level = 0.95) 
#extract matrix from array (the median layer of the cube (aka array))
overlap_1_matrix <- overlap_1$CI[ , , 2] 
#remove duplicate values of the matrix (upper triangle & diagonal portion of the matrix)
overlap_1_matrix[upper.tri(overlap_1_matrix, diag = TRUE)] <- NA
#check to see if the matrix extraction was correct and successful
overlap_1_matrix

# Convert overlap matrix into dataframe
pairwise_1 <- as.data.frame(overlap_1_matrix)

#data carpentry
pairwise_1$anteater_A <- rownames(pairwise_1) 
pairwise_1 <- pivot_longer(pairwise_1, cols = -anteater_A, names_to = 'anteater_B', values_to = 'overlap', values_drop_na = TRUE)
pairwise_1 <- left_join(pairwise_1, rename(METADATA, anteater_A = ID), by = "anteater_A")
pairwise_1 <- left_join(pairwise_1, rename(METADATA, anteater_B = ID), by = "anteater_B", suffix = c(".A", ".B"))

#add column to indicate which sexes that are being compared
DATA_pairwise_1 <- mutate(pairwise_1, sex_comparison = case_when(paste(Sex.A, Sex.B) == "Male Male" ~ "male-male",
                                                                         paste(Sex.A, Sex.B) == "Female Female" ~ "female-female",
                                                                         paste(Sex.A, Sex.B) == "Male Female" ~ "male-female",
                                                                         paste(Sex.A, Sex.B) == "Female Male" ~ "male-female"))
DATA_pairwise_1$site <- "1"

#subset dataframe exclude subadults from dataframe matrix
DATA_pairwise_1_adult <- DATA_pairwise_1[which(DATA_pairwise_1$Age.A != "Subadult"),]
DATA_pairwise_1_adult <- DATA_pairwise_1_adult[which(DATA_pairwise_1_adult$Age.B != "Subadult"),]
DATA_pairwise_1_adult$site <- "1"

#SITE 2
# Create a data frame from the overlap values
#calculate 95% overlap
overlap_2 <- overlap(object = AKDE_2, level = 0.95) 

#extract median layer from array (the median layer of the cube (aka array), in the form of a matrix)
overlap_2_matrix <- overlap_2$CI[ , , 2]

#remove duplicate values of the matrix (upper triangle & diagonal portion of the matrix)
overlap_2_matrix[upper.tri(overlap_2_matrix, diag = TRUE)] <- NA
#check to see if the matrix extraction was correct and successful
overlap_2_matrix


# Convert overlap matrix into dataframe
pairwise_2 <- as.data.frame(overlap_2_matrix)

#data carpentry
pairwise_2$anteater_A <- rownames(pairwise_2)
pairwise_2 <- pivot_longer(pairwise_2, cols = -anteater_A, names_to = 'anteater_B', values_to = 'overlap', values_drop_na = TRUE)
pairwise_2 <- left_join(pairwise_2, rename(METADATA, anteater_A = ID), by = "anteater_A")
pairwise_2 <- left_join(pairwise_2, rename(METADATA, anteater_B = ID), by = "anteater_B", suffix = c(".A", ".B"))

#add column to indicate which sexes that are being compared
DATA_pairwise_2 <- mutate(pairwise_2, sex_comparison = case_when(paste(Sex.A, Sex.B) == "Male Male" ~ "male-male",
                                                                         paste(Sex.A, Sex.B) == "Female Female" ~ "female-female",
                                                                         paste(Sex.A, Sex.B) == "Male Female" ~ "male-female",
                                                                         paste(Sex.A, Sex.B) == "Female Male" ~ "male-female"))
DATA_pairwise_2$site <- "2"

#subset dataframe to exclude subadults from dataframe matrix
DATA_pairwise_2_adult <- DATA_pairwise_2[which(DATA_pairwise_2$Age.A != "Subadult"),]
DATA_pairwise_2_adult <- DATA_pairwise_2_adult[which(DATA_pairwise_2_adult$Age.B != "Subadult"),]
DATA_pairwise_2_adult$site <- "2"

#combine both sites
DATA_pairwise <- bind_rows(DATA_pairwise_1, DATA_pairwise_2)
DATA_pairwise_adult <- bind_rows(DATA_pairwise_1_adult, DATA_pairwise_2_adult)

#RDS of pairwise have been saved to "RDS/pairwise" folder
```

##### Pairwise Analysis

```{r}
test <- glmer(overlap ~ sex_comparison + (1|site), family = binomial, data = DATA_pairwise)
test2 <- glmer(overlap ~ 1 + (1|site), family = binomial, data = DATA_pairwise)

anova(test, test2)

```

### Proximity

#### Site 1

```{r}
# create empty columns for where the result information will be added/filled into
DATA_pairwise_1$proximity_low <- NA
DATA_pairwise_1$proximity_est <- NA
DATA_pairwise_1$proximity_high <- NA

#Note: this will take a while (several days depending on the data)
# Using tryCatch
for(i in 1:nrow(DATA_pairwise_1)){
  ANIMAL_A <- as.character(DATA_pairwise_1[i, 'anteater_A']) # add as.character due to tibble format
  ANIMAL_B <- as.character(DATA_pairwise_1[i, 'anteater_B'])
  TRACKING_DATA.1 <- DATA[c(ANIMAL_A, ANIMAL_B)] # extract anteater by name, has extra layers .-. it doesnt work, that is why
  # line above is using as.character removes all the fluff because you just want the text string
  MODELS.1 <- list(FIT_1[ANIMAL_A][[1]], FIT_1[ANIMAL_B][[1]])
  PROXIMITy_1 <- tryCatch(
    {
      PROXIMITy_1 <- proximity(data = TRACKING_DATA.1, CTMM = MODELS.1, GUESS=ctmm(error=FALSE))},
    error=function(err){
      PROXIMITy_1 <- c(NA,NA,NA)
      return(PROXIMITy_1)
    }
  )
  DATA_pairwise_1[i, c("proximity_low")] <- PROXIMITy_1[1]
  DATA_pairwise_1[i, c("proximity_est")] <- PROXIMITy_1[2]
  DATA_pairwise_1[i, c("proximity_high")] <- PROXIMITy_1[3]
  write.csv(DATA_pairwise_1, "data/DATA_proximity_1.csv", row.names = FALSE)
  Sys.sleep(0.5) #this staggers each output by 0.5 seconds, a way to see the loop happening in real time
}

```

```{r}
#correct mismatch entry for sex_comparison to have - instead of : between the sex (male:male instead of male-male)
DATA_proximity_1 <- mutate(DATA_proximity_1, sex_comparison = case_when(
  paste(Sex.A, Sex.B) == "Male Male" ~ "male-male",
  paste(Sex.A, Sex.B) == "Female Female" ~ "female-female",
  paste(Sex.A, Sex.B) == "Male Female" ~ "male-female",
  paste(Sex.A, Sex.B) == "Female Male" ~ "male-female"))

```

#### Site 2
```{r}
# Using tryCatch
for(i in 1:nrow(DATA_pairwise_2)){
  ANIMAL_A <- as.character(DATA_pairwise_2[i, 'anteater_A']) # add as.character due to tibble format
  ANIMAL_B <- as.character(DATA_pairwise_2[i, 'anteater_B'])
  TRACKING_DATA_2 <- DATA[c(ANIMAL_A, ANIMAL_B)] # extract anteater by name, has extra layers .-. it doesnt work, that is why
  # line above is using as.character removes all the fluff because you just want the text string
  MODELS_2 <- list(FIT_2[ANIMAL_A][[1]], FIT_2[ANIMAL_B][[1]])
  PROXIMITY_2 <- tryCatch(
    {
      PROXIMITY_2 <- proximity(data = TRACKING_DATA_2, CTMM = MODELS_2, GUESS=ctmm(error=FALSE))},
    error=function(err){
      PROXIMITY_2 <- c(NA,NA,NA)
      return(PROXIMITY_2)
    }
  )
  DATA_pairwise_2[i, c("proximity_low")] <- PROXIMITY_2[1]
  DATA_pairwise_2[i, c("proximity_est")] <- PROXIMITY_2[2]
  DATA_pairwise_2[i, c("proximity_high")] <- PROXIMITY_2[3]
  write.csv(DATA_pairwise_2, "data/DATA.PROXIMITY_2.csv", row.names = FALSE)
    Sys.sleep(0.5) #this staggers each output by 0.5 seconds, a way to see the loop happening in real time
}


```

```{r}
#combine the proximity of the two sites into one dataframe
DATA_proximity <- bind_rows(DATA_proximity_1, DATA_proximity_2)

#identify the pairs that had a proximity above/below 1
proximity_above1 <- DATA_proximity[which(DATA_proximity$proximity_low > 1),]
proximity_below1 <- DATA_proximity[which(DATA_proximity$proximity_high < 1),]

#remove pairs with no overlap
proximity_below1 <- proximity_below1[proximity_below1$overlap !=0,]

#RDS of proximity have been saved to "RDS/proximity" folder
```

#### Distance

```{r}
#subset pairs that had a proximity above/below 1
# Christoffer/Kyle
pair1 <- DATA[c(12,24)]
FIT_pair1 <- FIT_1[c(5,8)]
distance_pair1 <- distances(pair1, FIT_pair1) # distance measurement and time between the pair

# Christoffer/Elaine
pair2 <- DATA[c(12,15)]
FIT_pair2 <- FIT_1[c(5,6)]
distance_pair2 <- distances(pair2, FIT_pair2) # distance measurement and time between the pair

# Bumpus/Kyle
pair3 <- DATA[c(9,24)]
FIT_pair3 <- FIT_1[c(3,8)]
distance_pair3 <- distances(pair3, FIT_pair3) # distance measurement and time between the pair

# Elaine/Little Rick
pair4 <- DATA[c(15,27)]
FIT_pair4<- FIT_1[c(6,9)]
distance_pair4 <- distances(pair4, FIT_pair4) # distance measurement and time between the pair

# Bumpus/Makao
pair5 <- DATA[c(9,29)]
FIT_pair5 <- FIT_1[c(3,10)]
distance_pair5 <- distances(pair5, FIT_pair5) # distance measurement and time between the pair

# Bumpus/Puji
pair6 <- DATA[c(9,36)]
FIT_pair6 <- FIT_1[c(3,11)]
distance_pair6 <- distances(pair6, FIT_pair6) # distance measurement and time between the pair

# Elaine/Rodolfo
pair7 <- DATA[c(15,38)]
FIT_pair7 <- FIT_1[c(6,12)]
distance_pair7 <- distances(pair7, FIT_pair7) # distance measurement and time between the pair

# Annie/Larry
pair8 <- DATA[c(2,25)] 
FIT_pair8 <- FIT_2[c(1,5)]
distance_pair8 <- distances(pair8, FIT_pair8) # distance measurement and time between the pair

# Larry/Reid
pair9 <- DATA[c(25,37)] 
FIT_pair9 <- FIT_2[c(5,9)]
distance_pair9 <- distances(pair9, FIT_pair9) # distance measurement and time between the pair

# Margaret/Thomas
pair10 <- DATA[c(30,42)] 
FIT_pair10 <- FIT_2[c(7,11)]
distance_pair10 <- distances(pair10, FIT_pair10) # distance measurement and time between the pair

# Reid/Thomas
pair11<- DATA[c(37,42)] 
FIT_pair11 <- FIT_2[c(9,11)]
distance_pair11 <- distances(pair11, FIT_pair11) # distance measurement and time between the pair

# Maria/Sheron
pair12 <- DATA[c(31,41)] 
FIT_pair12 <- FIT_2[c(8,10)]
distance_pair12 <- distances(pair12, FIT_pair12) # distance measurement and time between the pair

#RDS of distances have been saved to "RDS/distance" folder
```


### Correlative Movement

#### data wrangling

```{r}
#data carpentry
Bumpus <- DATA$Bumpus
Christoffer <- DATA$Christoffer
Elaine <- DATA$Elaine
Kyle <- DATA$Kyle
Little_rick <- DATA$`Little Rick`
Makao <- DATA$Makao
Puji <- DATA$Puji
Rodolfo <- DATA$Rodolfo
Annie <- DATA$Annie
Larry <- DATA$`Larry 267`
Margaret <- DATA$Margaret
Reid <- DATA$Reid
Thomas <- DATA$Thomas
Maria <- DATA$Maria
Sheron <- DATA$Sheron

#create a dataframe of an individuals GPS coordinates
Bumpus_GPS <- data.frame(timestamp = round_date(Bumpus$timestamp, "20 minutes"),
                          Bumpus.x = Bumpus$longitude,
                          Bumpus.y = Bumpus$latitude)
Christoffer_GPS <- data.frame(timestamp = round_date(Christoffer$timestamp, "20 minutes"),
                               Christoffer.x = Christoffer$longitude,
                               Christoffer.y = Christoffer$latitude)
Elaine_GPS <- data.frame(timestamp = round_date(Elaine$timestamp, "20 minutes"),
                          Elaine.x = Elaine$longitude,
                          Elaine.y = Elaine$latitude)
Kyle_GPS <- data.frame(timestamp = round_date(Kyle$timestamp, "20 minutes"),
                        Kyle.x = Kyle$longitude,
                        Kyle.y = Kyle$latitude)
Little_rick_GPS <- data.frame(timestamp = round_date(Little_rick$timestamp, "20 minutes"),
                               Little_rick.x = Little_rick$longitude,
                               Little_rick.y = Little_rick$latitude)
Makao_GPS <- data.frame(timestamp = round_date(Makao$timestamp, "20 minutes"),
                         Makao.x = Makao$longitude,
                         Makao.y = Makao$latitude)
Puji_GPS <- data.frame(timestamp = round_date(Puji$timestamp, "20 minutes"),
                        Puji.x = Puji$longitude,
                        Puji.y = Puji$latitude)
Rodolfo_GPS <- data.frame(timestamp = round_date(Rodolfo$timestamp, "20 minutes"),
                           Rodolfo.x = Rodolfo$longitude,
                           Rodolfo.y = Rodolfo$latitude)
Annie_GPS <- data.frame(timestamp = round_date(Annie$timestamp, "20 minutes"),
                         Annie.x = Annie$longitude,
                         Annie.y = Annie$latitude)
Larry_GPS <- data.frame(timestamp = round_date(Larry$timestamp, "20 minutes"),
                         Larry.x = Larry$longitude,
                         Larry.y = Larry$latitude)
Margaret_GPS <- data.frame(timestamp = round_date(Margaret$timestamp, "20 minutes"),
                            Margaret.x = Margaret$longitude,
                            Margaret.y = Margaret$latitude)
Reid_GPS <- data.frame(timestamp = round_date(Reid$timestamp, "20 minutes"),
                        Reid.x = Reid$longitude,
                        Reid.y = Reid$latitude)
Thomas_GPS <- data.frame(timestamp = round_date(Thomas$timestamp, "20 minutes"),
                          Thomas.x = Thomas$longitude,
                          Thomas.y = Thomas$latitude)
Maria_GPS <- data.frame(timestamp = round_date(Maria$timestamp, "20 minutes"),
                         Maria.x = Maria$longitude,
                         Maria.y = Maria$latitude)
Sheron_GPS <- data.frame(timestamp = round_date(Sheron$timestamp, "20 minutes"),
                          Sheron.x = Sheron$longitude,
                          Sheron.y = Sheron$latitude)

#combine the GPS coordinates of pairs together
pair1_GPS <- merge(Christoffer_GPS, Kyle_GPS)
pair1_GPS <- pair1_GPS[, c(1,2,4,3,5)]
pair1_GPS <- pair1_GPS[!duplicated(pair1_GPS$timestamp),]

pair2_GPS <- merge(Christoffer_GPS, Elaine_GPS)
pair2_GPS <- pair2_GPS[, c(1,2,4,3,5)]
pair2_GPS <- pair2_GPS[!duplicated(pair2_GPS$timestamp),]

pair3_GPS <- merge(Bumpus_GPS, Kyle_GPS)
pair3_GPS <- pair3_GPS[, c(1,2,4,3,5)]
pair3_GPS <- pair3_GPS[!duplicated(pair3_GPS$timestamp),]

pair4_GPS <- merge(Elaine_GPS, Little_rick_GPS)
pair4_GPS <- pair4_GPS[, c(1,2,4,3,5)]
pair4_GPS <- pair4_GPS[!duplicated(pair4_GPS$timestamp),]

pair5_GPS <- merge(Bumpus_GPS, Makao_GPS)
pair5_GPS <- pair5_GPS[, c(1,2,4,3,5)]
pair5_GPS <- pair5_GPS[!duplicated(pair5_GPS$timestamp),]

pair6_GPS <- merge(Bumpus_GPS, Puji_GPS)
pair6_GPS <- pair6_GPS[, c(1,2,4,3,5)]
pair6_GPS <- pair6_GPS[!duplicated(pair6_GPS$timestamp),]

pair7_GPS <- merge(Elaine_GPS, Rodolfo_GPS)
pair7_GPS <- pair7_GPS[, c(1,2,4,3,5)]
pair7_GPS <- pair7_GPS[!duplicated(pair7_GPS$timestamp),]

pair8_GPS <- merge(Annie_GPS, Larry_GPS)
pair8_GPS <- pair8_GPS[, c(1,2,4,3,5)]
pair8_GPS <- pair8_GPS[!duplicated(pair8_GPS$timestamp),]

pair9_GPS <- merge(Larry_GPS, Reid_GPS)
pair9_GPS <- pair9_GPS[, c(1,2,4,3,5)]
pair9_GPS <- pair9_GPS[!duplicated(pair9_GPS$timestamp),]

pair10_GPS <- merge(Margaret_GPS, Thomas_GPS)
pair10_GPS <- pair10_GPS[, c(1,2,4,3,5)]
pair10_GPS <- pair10_GPS[!duplicated(pair10_GPS$timestamp),]

pair11_GPS <- merge(Reid_GPS, Thomas_GPS)
pair11_GPS <- pair11_GPS[, c(1,2,4,3,5)]
pair11_GPS <- pair11_GPS[!duplicated(pair11_GPS$timestamp),]

pair12_GPS <- merge(Maria_GPS, Sheron_GPS)
pair12_GPS <- pair12_GPS[, c(1,2,4,3,5)]
pair12_GPS <- pair12_GPS[!duplicated(pair12_GPS$timestamp),]

```

#### CorrMove Analysis

```{r}
#Create corrData object.
cdAnteater_pair1 <- as.corrData(pair1_GPS)
#Estimate the partition points for the khulan data, with W=25
prtsAnteater_pair1 <- findPrts(cdAnteater_pair1, W=5, IC = 2)
#Get the MCI estimates and selected model conditional on the data and partition points
cmAnteater_pair1 <- corrMove(cdAnteater_pair1, prtsAnteater_pair1)

#Create corrData object.
cdAnteater_pair2 <- as.corrData(pair2_GPS)
#Estimate the partition points for the khulan data, with W=25
prtsAnteater_pair2 <- findPrts(cdAnteater_pair2, W=5, IC = 2)
#Get the MCI estimates and selected model conditional on the data and partition points
cmAnteater_pair2 <- corrMove(cdAnteater_pair2, prtsAnteater_pair2)

#Create corrData object.
cdAnteater_pair3 <- as.corrData(pair3_GPS)
#Estimate the partition points for the khulan data, with W=25
prtsAnteater_pair3 <- findPrts(cdAnteater_pair3, W=5, IC = 2)
#Get the MCI estimates and selected model conditional on the data and partition points
cmAnteater_pair3 <- corrMove(cdAnteater_pair3, prtsAnteater_pair3)

#Create corrData object.
cdAnteater_pair4 <- as.corrData(pair4_GPS)
#Estimate the partition points for the khulan data, with W=25
prtsAnteater_pair4 <- findPrts(cdAnteater_pair4, W=5, IC = 2)
#Get the MCI estimates and selected model conditional on the data and partition points
cmAnteater_pair4 <- corrMove(cdAnteater_pair4, prtsAnteater_pair4)

#Create corrData object.
cdAnteater_pair5 <- as.corrData(pair5_GPS)
#Estimate the partition points for the khulan data, with W=25
prtsAnteater_pair5 <- findPrts(cdAnteater_pair5, W=5, IC = 2)
#Get the MCI estimates and selected model conditional on the data and partition points
cmAnteater_pair5 <- corrMove(cdAnteater_pair5, prtsAnteater_pair5)

#Create corrData object.
cdAnteater_pair6 <- as.corrData(pair6_GPS)
#Estimate the partition points for the khulan data, with W=25
prtsAnteater_pair6 <- findPrts(cdAnteater_pair6, W=5, IC = 2)
#Get the MCI estimates and selected model conditional on the data and partition points
cmAnteater_pair6 <- corrMove(cdAnteater_pair6, prtsAnteater_pair6)

#Create corrData object.
cdAnteater_pair7 <- as.corrData(pair7_GPS)
#Estimate the partition points for the khulan data, with W=25
prtsAnteater_pair7 <- findPrts(cdAnteater_pair7, W=5, IC = 2)
#Get the MCI estimates and selected model conditional on the data and partition points
cmAnteater_pair7 <- corrMove(cdAnteater_pair7, prtsAnteater_pair7)

#Create corrData object.
cdAnteater_pair8 <- as.corrData(pair8_GPS)
#Estimate the partition points for the khulan data, with W=25
prtsAnteater_pair8 <- findPrts(cdAnteater_pair8, W=5, IC = 2)
#Get the MCI estimates and selected model conditional on the data and partition points
cmAnteater_pair8 <- corrMove(cdAnteater_pair8, prtsAnteater_pair8)

#Create corrData object.
cdAnteater_pair9 <- as.corrData(pair9_GPS)
#Estimate the partition points for the khulan data, with W=25
prtsAnteater_pair9 <- findPrts(cdAnteater_pair9, W=5, IC = 2)
#Get the MCI estimates and selected model conditional on the data and partition points
cmAnteater_pair9 <- corrMove(cdAnteater_pair9, prtsAnteater_pair9)

#Create corrData object.
cdAnteater_pair10 <- as.corrData(pair10_GPS)
#Estimate the partition points for the khulan data, with W=25
prtsAnteater_pair10 <- findPrts(cdAnteater_pair10, W=5, IC = 2)
#Get the MCI estimates and selected model conditional on the data and partition points
cmAnteater_pair10 <- corrMove(cdAnteater_pair10, prtsAnteater_pair10)

#Create corrData object.
cdAnteater_pair11 <- as.corrData(pair11_GPS)
#Estimate the partition points for the khulan data, with W=25
prtsAnteater_pair11 <- findPrts(cdAnteater_pair11, W=5, IC = 2)
#Get the MCI estimates and selected model conditional on the data and partition points
cmAnteater_pair11 <- corrMove(cdAnteater_pair11, prtsAnteater_pair11)

#Create corrData object.
cdAnteater_pair12 <- as.corrData(pair12_GPS)
#Estimate the partition points for the khulan data, with W=25
prtsAnteater_pair12 <- findPrts(cdAnteater_pair12, W=5, IC = 2)
#Get the MCI estimates and selected model conditional on the data and partition points
cmAnteater_pair12 <- corrMove(cdAnteater_pair12, prtsAnteater_pair12)

#RDS of correlative movement have been saved to "RDS/correlative movement" folder
```

# R Packages

```{r}
sessionInfo()
```

